/* tslint:disable */
/* eslint-disable */
/**
 * Mail Server Manager API
 * This is an API specification used to manager a database that is used by an Exim4 server as your accounts and domains.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gibalmeida@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

